[package]
name = "color_palette"
version = "0.1.0"
authors = ["Clark Moody <clark@clarkmoody.com>"]
edition = "2021"
publish = false

[dependencies]
iced.workspace = true
iced.features = ["canvas"]

palette.workspace = true
