[package]
name = "sierpinski_triangle"
version = "0.1.0"
authors = ["xkenmon <xkenmon@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
iced.workspace = true
iced.features = ["debug", "canvas"]

rand = "0.8"
